# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - flaskappcarri

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Test app
      run: python src/test_app.py
      
    - name: Send Slack notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: proyecto-ci-cd
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Test Results for ${{ github.repository }} Commit: ${{ github.sha }} --> Test fallido }}'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    - name: Send Slack notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: proyecto-ci-cd
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Test Results for ${{ github.repository }} Commit: ${{ github.sha }} --> Test exitoso }}'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      
  
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to registry
      uses: docker/login-action@v2
      with:
        registry: https://flaskcontainercarri.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_2c74be2d87f947a7b973ad08d8aa99a6 }}
        password: ${{ secrets.AzureAppService_ContainerPassword_0cd94a71fd314a16a04ba75b89c428ef }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: flaskcontainercarri.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2c74be2d87f947a7b973ad08d8aa99a6 }}/flaskcontainercarri.azurecr.io/flask-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'flaskappcarri'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_1c91d987716640b29d9e3112acdc2f17 }}
        images: 'flaskcontainercarri.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_2c74be2d87f947a7b973ad08d8aa99a6 }}/flaskcontainercarri.azurecr.io/flask-app:${{ github.sha }}'
    
    - name: Send Slack notification
      if: ${{ failure() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: proyecto-ci-cd
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Test Results for ${{ github.repository }} Commit: ${{ github.sha }} --> Test fallido }}'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
      
    - name: Send Slack notification
      if: ${{ success() }}
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_CHANNEL: proyecto-ci-cd
        SLACK_COLOR: ${{ job.status }} # or a specific color like 'good' or '#ff00ff'
        SLACK_ICON: https://github.com/rtCamp.png?size=48
        SLACK_MESSAGE: 'Test Results for ${{ github.repository }} Commit: ${{ github.sha }} --> Test exitoso }}'
        SLACK_TITLE: Post Title
        SLACK_USERNAME: rtCamp
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
