# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Flask Web Appp

on:
  push:
    branches: [ "main" ]

permissions:
    id-token: write
    contents: read
    
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
          
    - name: Install Azure cli
      run: |
        sudo apt-get install ca-certificates curl apt-transport-https lsb-release gnupg
        curl -sL https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor | sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
        AZ_REPO=$(lsb_release -cs)
        echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" | sudo tee /etc/apt/sources.list.d/azure-cli.list
        sudo apt-get update
        sudo apt-get install azure-cli
        
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
      
    - uses: azure/docker-login@v1
      with:
        login-server: flaskcontainercarri.azurecr.io
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}
    
    - run: |
        docker build . -t flaskcontainercarri.azurecr.io/flask-app:${{ github.sha }}
        docker push flaskcontainercarri.azurecr.io/flask-app:${{ github.sha }} 
    
    - uses: azure/webapps-deploy@v2
      with:
        app-name: 'flaskappcarri'
        images: 'flaskcontainercarri.azurecr.io/flask-app:${{ github.sha }}'
    
    - name: Azure logout
      run: |
        az logout
 
