# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Build Flask Web App

on:
  push:
    branches: [ "main" ]
    
jobs:
  build:
    name: Build project
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
            
    - name: Build Docker image
      run: docker build -t juancru68/flask_app .
      
    - name: Test app with unit tests
      run: |
        docker run --rm juancru68/flask_app:latest python src/test_app.py

    - name: Push to Docker Hub
      uses: docker/build-push-action@v1 # Info: https://github.com/docker/build-push-action/tree/releases/v1#tags
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: ${{ secrets.DOCKERHUB_REPOSITORY }}
        tags: latest

 
